In [3]:
#1.Debug the given code
import pandas as pd

data = {'Feature1': ['10', '20', 'Thirty'],  # 'Thirty' is not a valid number
        'Feature2': [5.5, 6.7, 8.9]}

df = pd.DataFrame(data)
df['Feature1'] = df['Feature1'].astype(str)  # Error: Cannot convert 'Thirty' to int

print(df)

#ans: conerted the data type from int to str

  Feature1  Feature2
0       10       5.5
1       20       6.7
2   Thirty       8.9


In [5]:
#2.
import pandas as pd

data = {'A': [1, 2, None],  # Missing value
        'B': [4, None, 6]}  # Missing value

df = pd.DataFrame(data)
mean_value = df.mean()
df = df.fillna(mean_value)  # Error: fillna() does not modify in place

#ans: df is assigent to the fillna()

print(df)



     A    B
0  1.0  4.0
1  2.0  5.0
2  1.5  6.0


In [18]:
#3.
from sklearn.linear_model import LinearRegression
import numpy as np

X = np.array([[1],[2], [3], [4], [5]])  # Error: X should be 2D 
y = np.array([2, 4, 6, 8, 10])

model = LinearRegression()
model.fit(X, y)

print(model.predict([[6]]))

[12.]


In [10]:
#4.
from sklearn.preprocessing import StandardScaler
import numpy as np

data = np.array([[10], [20], [30], [40], [50]])  # Error: Should be 2D

scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

print(scaled_data)


[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]


In [24]:
#5.
from sklearn.linear_model import LogisticRegression

X = [[1, 2], [3, 4], [5, 6]]
y = ['yes', 'no', 'yes']  # Error: Labels should be numeric

#ans:
y = [1 if i =="yes" else 0 for i in y ]  


model = LogisticRegression()
model.fit(X, y)

print(model.predict([[3, 5]]))

[1]


In [28]:
#6.import pandas as pd
from sklearn.preprocessing import OneHotEncoder

df = pd.DataFrame({'Category': ['A', 'B', 'C', 'A']})

encoder = OneHotEncoder()
encoded = encoder.fit_transform(df[['Category']])  # Error: Data should be reshaped
print(encoded)

#ans: ['Category'] is converted to [['Category']]

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4 stored elements and shape (4, 3)>
  Coords	Values
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 0)	1.0


In [31]:
#6.
from sklearn.model_selection import train_test_split

X = [[1, 2], [3, 4], [5, 6], [7, 8]]
y = [0, 1, 0, 1]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

print(X_train)
print(y_train)
print(X_test)
print(y_test)


[[7, 8], [5, 6], [3, 4]]
[1, 0, 1]
[[1, 2]]
[0]


In [37]:
#7.from sklearn.linear_model import LogisticRegression

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["yes", "no", "yes"]  # Error: LogisticRegression expects numerical labels

#y_train = pd.get_dummies(y_train,drop_first=True)

#ans:
y_train = [1 if i =="yes" else 0 for i in y_train ]  


model = LogisticRegression()
model.fit(X_train, y_train)

print(model.predict([[2, 3]]))


[1]


In [43]:
#8.
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.impute import SimpleImputer

# Creating a dataset with missing values
X_train = np.array([[1, 2], [3, np.nan], [5, 6]])
y_train = np.array([10, 20, 30])

imputer = SimpleImputer(strategy ='mean')
X_train = imputer.fit_transform(X_train)

model = LinearRegression()
model.fit(X_train, y_train)  

print(X_train)
print(model.predict([[2, 3]]))

#ans: SimpleImputer is used to fill the missing values 

[[1. 2.]
 [3. 4.]
 [5. 6.]]
[15.]


In [46]:
#9.
from sklearn.tree import DecisionTreeClassifier

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["spam", "ham", "spam"]  # Error: String labels not allowed

#ans:
y_train = [1 if i =="spam" else 0 for i in y_train ]  


model = DecisionTreeClassifier()
model.fit(X_train, y_train)

print(model.predict([[1, 2]]))



[1]


In [50]:
#10.
from sklearn.svm import SVC

X_train = [[1, 100], [2, 200], [3, 300]]
y_train = [0, 1, 0]

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

model = SVC()

model.fit(X_train_scaled, y_train)

print(model.predict([[1, 150]]))  # Unreliable output due to large-scale difference

print(X_train_scaled)


#ans: Since you have mentioned the Large-scale diff StandarScaler is used 

[0]
[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]
