In [1]:
import  numpy as np
import matplotlib.pyplot as plt
import pandas as pd 

In [2]:
dataset = pd.read_csv('50_Startups.csv')

In [3]:
dataset = pd.get_dummies (dataset,drop_first=True)

In [4]:
indep = dataset[['R&D Spend','Administration','Marketing Spend','State_Florida','State_New York']]
dep = dataset[['Profit']]

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(indep,dep,test_size = 0.03, random_state = 0)

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [7]:
scy = StandardScaler()
Y_train = scy.fit_transform(Y_train)
Y_test = scy.transform(Y_test)

In [8]:
X_train

array([[ 0.61890562, -0.38013263,  0.13861574,  1.4832397 , -0.74053163],
       [-0.98327935, -1.35535013, -0.38862504,  1.4832397 , -0.74053163],
       [ 1.73425145, -0.73613   ,  1.59566287,  1.4832397 , -0.74053163],
       [-0.02624149,  0.27057301,  1.14943145, -0.67419986,  1.35038121],
       [-1.14915406, -2.06228556, -0.21914584, -0.67419986,  1.35038121],
       [-0.2637163 ,  1.20638107, -1.01010083, -0.67419986,  1.35038121],
       [ 0.01460224,  0.0791039 ,  0.74302355,  1.4832397 , -0.74053163],
       [ 1.48892049, -1.10362728,  1.2552591 ,  1.4832397 , -0.74053163],
       [-0.38584812, -0.66409304,  0.02022426,  1.4832397 , -0.74053163],
       [-0.59104359, -1.34266528, -0.05408284, -0.67419986,  1.35038121],
       [ 0.04348371,  0.88363854, -0.63656047,  1.4832397 , -0.74053163],
       [-0.58212466,  1.39446675, -0.01104934, -0.67419986, -0.74053163],
       [ 0.39890502, -0.24518416,  0.67456408,  1.4832397 , -0.74053163],
       [ 1.23330717,  0.93616388,  0.9

In [9]:
X_test

array([[-0.15732686,  2.33458021, -0.76616448,  1.4832397 , -0.74053163],
       [ 0.59204127, -1.08860002,  0.30637696, -0.67419986, -0.74053163]])

In [10]:
Y_train

array([[ 0.85568777],
       [-0.83403899],
       [ 1.96683122],
       [-0.16111032],
       [-0.74920458],
       [-0.34720796],
       [-0.02894717],
       [ 1.3519479 ],
       [-0.36463469],
       [-0.37203952],
       [-0.14317436],
       [-0.36626994],
       [ 0.31518167],
       [ 1.09386728],
       [ 0.52133648],
       [-1.15240018],
       [-1.87585982],
       [-0.2601267 ],
       [ 0.45491758],
       [-0.28651635],
       [-0.34858599],
       [ 0.38260023],
       [-0.98985525],
       [ 0.17191586],
       [-1.03287578],
       [ 1.00629757],
       [ 0.56349611],
       [-0.10185313],
       [ 1.12449762],
       [ 0.34247204],
       [-0.82313046],
       [-2.39502172],
       [ 1.98517376],
       [ 0.74349548],
       [-0.53354475],
       [-0.07346889],
       [ 1.10301567],
       [-0.06896902],
       [-0.51477238],
       [-0.00518598],
       [ 0.27833089],
       [ 0.94566087],
       [-0.7547271 ],
       [-1.53413758],
       [ 1.76530984],
       [ 1

In [11]:
Y_test

array([[-0.20379499],
       [ 0.80962429]])

In [12]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid = {'criterion':['mse','mae','friedman_mse'],
'max_features': ['auto','sqrt','log2'],
'splitter':['best','random']}

In [13]:
grid = GridSearchCV(DecisionTreeRegressor(), param_grid, refit = True, verbose = 3,n_jobs=-1)
# fitting the model for grid search
grid.fit(X_train, Y_train)

Fitting 5 folds for each of 18 candidates, totalling 90 fits


C:\Users\User\.conda\envs\myenv\Lib\site-packages\sklearn\model_selection\_validation.py:542: FitFailedWarning: 
70 fits failed out of a total of 90.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
4 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\User\.conda\envs\myenv\Lib\site-packages\sklearn\model_selection\_validation.py", line 890, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\User\.conda\envs\myenv\Lib\site-packages\sklearn\base.py", line 1344, in wrapper
    estimator._validate_params()
  File "C:\Users\User\.conda\envs\myenv\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\User\.c

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['mse', 'mae', 'friedman_mse'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [14]:
# print best parameter after tuning
#print(grid.best_params_)
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test)
# print classification report
from sklearn.metrics import r2_score
r_score=r2_score(Y_test,grid_predictions)
print("The R_score value for best parameter {}:".format(grid.best_params_),r_score)

The R_score value for best parameter {'criterion': 'friedman_mse', 'max_features': 'log2', 'splitter': 'best'}: 0.9887115876456188


In [15]:
table=pd.DataFrame.from_dict(re)

In [16]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.000598,4.883449e-04,0.000000,0.000000e+00,mse,auto,best,"{'criterion': 'mse', 'max_features': 'auto', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
1,0.000598,4.885387e-04,0.000000,0.000000e+00,mse,auto,random,"{'criterion': 'mse', 'max_features': 'auto', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
2,0.000600,4.895515e-04,0.000000,0.000000e+00,mse,sqrt,best,"{'criterion': 'mse', 'max_features': 'sqrt', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
3,0.000598,4.885788e-04,0.000000,0.000000e+00,mse,sqrt,random,"{'criterion': 'mse', 'max_features': 'sqrt', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
4,0.000599,4.887724e-04,0.000000,0.000000e+00,mse,log2,best,"{'criterion': 'mse', 'max_features': 'log2', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
5,0.000399,4.891620e-04,0.000000,0.000000e+00,mse,log2,random,"{'criterion': 'mse', 'max_features': 'log2', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
6,0.000399,4.887538e-04,0.000000,0.000000e+00,mae,auto,best,"{'criterion': 'mae', 'max_features': 'auto', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
7,0.000997,1.291868e-06,0.000000,0.000000e+00,mae,auto,random,"{'criterion': 'mae', 'max_features': 'auto', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
8,0.000199,3.988266e-04,0.000000,0.000000e+00,mae,sqrt,best,"{'criterion': 'mae', 'max_features': 'sqrt', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
9,0.000199,3.989220e-04,0.000000,0.000000e+00,mae,sqrt,random,"{'criterion': 'mae', 'max_features': 'sqrt', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5


In [17]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:28
BMI:56
Children:1
Sex Male 0 or 1:1
Smoker Yes 0 or 1:0


In [18]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
#change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[1.3519479]


In [19]:
import pickle
filename="finalized_model_DT.sav"

In [20]:
pickle.dump(grid,open(filename,'wb'))

In [21]:
preinput=sc.transform([[1300,12000,4000,0,1]])

C:\Users\User\.conda\envs\myenv\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [22]:
preinput

array([[-1.55888979, -4.09490444, -1.69649936, -0.67419986,  1.35038121]])

In [23]:
loaded_model=pickle.load(open("finalized_model_DT.sav",'rb'))
result=loaded_model.predict(preinput)

In [24]:
result

array([-1.87585982])

In [25]:
preoutput=scy.inverse_transform([result])

In [26]:
preoutput

array([[35673.41]])